"use strict";
jest.mock('../../utils/stripe.util', () => ({}));
jest.mock('../../services/customerPortal/subscriptionEmailNotifications.service', () => ({}));
jest.mock('../../services/customerPortal/subscriptionAddOnPayment.service', () => ({ recoverAddOnPayment: jest.fn() }));
const mongoose = require('mongoose');
const Subscription = require('../../models/subscription.model');
const Delivery = require('../../models/subscriptionDelivery.model');
const Mutation = require('../../models/subscriptionMutation.model');
const Payment = require('../../models/payment.model');
const Order = require('../../models/order.model');
const Notification = require('../../models/customerNotification.model');
const settings = require('../../services/subscriptionSettings.service');
const { recoverAddOnPayment } = require('../../services/customerPortal/subscriptionAddOnPayment.service');
const { AddNextDeliveryAddOn } = require('../../services/customerPortal/customerSubscriptions.service');
afterEach(() => jest.restoreAllMocks());
it('dispatch during payment returns reconciliation without changing delivery fulfillment', async () => {
  const order = { _id: 'order', status: 'paid', deliveryStatus: 'ordered' };
  const delivery = { _id: 'delivery', status: 'generated', scheduledDate: new Date(Date.now() + 3 * 86400000), order, addOns: [] };
  jest.spyOn(Subscription, 'findOne').mockResolvedValue({ _id: 's', customer: 'c', status: 'active' });
  jest.spyOn(Mutation, 'findOne').mockResolvedValue({ operationId: 'op', addOnSnapshot: { deliveryId: 'delivery', amountMinor: 250, items: [] } });
  jest.spyOn(Delivery, 'findOne').mockResolvedValueOnce(null).mockReturnValueOnce({ populate: async () => delivery });
  jest.spyOn(settings, 'getOrCreateSettings').mockResolvedValue({ cutoffDaysBefore: 0, cutoffTime: '23:59' });
  recoverAddOnPayment.mockImplementation(async () => {
    order.deliveryStatus = 'dispatched';
    return { ok: true, paymentIntent: { id: 'paid-intent', status: 'succeeded' } };
  });
  jest.spyOn(mongoose, 'startSession').mockResolvedValue({ withTransaction: async fn => fn(), endSession: async () => {} });
  jest.spyOn(Delivery, 'findById').mockReturnValue({ session: async () => delivery });
  jest.spyOn(Payment, 'findOneAndUpdate').mockResolvedValue({});
  jest.spyOn(Order, 'findOne').mockReturnValue({ session: async () => order });
  jest.spyOn(Notification, 'create').mockResolvedValue({});
  const result = await AddNextDeliveryAddOn({ customerId: 'c', subscriptionId: 's', operationId: 'op' });
  expect(result.success).toBe(false);
  expect(result.data.paymentOutcome).toBe('succeeded');
  expect(result.data.reconciliationRequired).toBe(true);
  expect(Notification.create).not.toHaveBeenCalled();
  expect(result.data.chargedMinor).toBe(250);
  expect(delivery.addOns).toHaveLength(0);
  expect(Payment.findOneAndUpdate).toHaveBeenCalledTimes(1);
});
