const BUSINESS_LOGO_MAX_BYTES = 2 * 1024 * 1024;
const BUSINESS_LOGO_MAX_DATA_URL_LENGTH =
  Math.ceil((BUSINESS_LOGO_MAX_BYTES * 4) / 3) + 200;

module.exports = {
  BUSINESS_LOGO_MAX_BYTES,
  BUSINESS_LOGO_MAX_DATA_URL_LENGTH,
};
